# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:

  build-node-6:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - node6-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node6-dependencies-{{ checksum "package.json" }}
      - run: mkdir ~/junit
      - run: npm run test
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

  build-node-7:
    docker:
      - image: circleci/node:7
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - node7-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node7-dependencies-{{ checksum "package.json" }}
      - run: mkdir ~/junit
      - run: npm run test
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit


  build-node-8:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - node8-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node8-dependencies-{{ checksum "package.json" }}
      - run: mkdir ~/junit
      - run: npm run test
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

  build-node-10:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - node10-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node10-dependencies-{{ checksum "package.json" }}
      - run: mkdir ~/junit
      - run: npm run test
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
